name: _Build docker image

on:
  workflow_call:

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    env:
      VAR_NODE_REGISTRY: ${{ vars.NODE_REGISTRY }}
      VAR_NODE_REPOSITORY: ${{ vars.NODE_REPOSITORY }}
      SECRET_NODE_REGISTRY_USERNAME: ${{ secrets.NODE_REGISTRY_USERNAME }}
      SECRET_NODE_REGISTRY_PASSWORD: ${{ secrets.NODE_REGISTRY_PASSWORD }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.5.0

      - name: Get branch name and commit SHA
        id: get-branch
        uses: ./.github/actions/get-branch

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: node
          path: target/release/node

      - name: Build docker image
        run: |
          chmod +x target/release/node
          docker build --tag node:${{ steps.get-branch.outputs.sha_short }} -f docker/Dockerfile .

      - name: Login to docker registry
        if: env.VAR_NODE_REPOSITORY != '' && env.SECRET_NODE_REGISTRY_USERNAME != '' && env.SECRET_NODE_REGISTRY_PASSWORD != ''
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.NODE_REGISTRY }}
          username: ${{ secrets.NODE_REGISTRY_USERNAME }}
          password: ${{ secrets.NODE_REGISTRY_PASSWORD }}

      - name: Push docker image to the repository
        if: env.VAR_NODE_REPOSITORY != '' && env.SECRET_NODE_REGISTRY_USERNAME != '' && env.SECRET_NODE_REGISTRY_PASSWORD != ''
        run: |
          docker tag node:${{ steps.get-branch.outputs.sha_short }} ${{ vars.VAR_NODE_REPOSITORY }}:${{ steps.get-branch.outputs.sha_short }}
          docker push ${{ vars.VAR_NODE_REPOSITORY }}:${{ steps.get-branch.outputs.sha_short }}
