name: Build artifact and push docker image

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-unit-tests:
    name: Run unit tests
    uses: ./.github/workflows/_run-unit-tests.yaml
    secrets: inherit

  build-node-artifact:
    needs: ['run-unit-tests']
    name: Build node artifact
    uses: ./.github/workflows/_build-node-artifact.yaml
    secrets: inherit

  build-docker-image:
    needs: ['build-node-artifact']
    name: Build node artifact
    uses: ./.github/workflows/_build-docker-image.yaml
    secrets: inherit

  set-success-status:
    needs: ['build-docker-image']
    name: Set status of the commit to 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.5.0

      - name: Get branch name and commit SHA
        id: get-branch
        uses: ./.github/actions/get-branch

      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.get-branch.outputs.sha_short }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "build",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail