name: Build node binary

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.5.0

      - name: Build binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: node
          path: target/release/node-template
          if-no-files-found: error
          retention-days: 7
