name: F02. Delete feature environment

on:
  pull_request:
    types: [labeled, closed]

concurrency:
  group: feature-env
  cancel-in-progress: false

jobs:
  create-feature-env:
    if: >
      github.event.action == 'labeled' && github.event.label.name == 'delete-feature-env' ||
      github.event.action == 'closed'
    runs-on: ubuntu-22.04
    env:
      VAR_NODE_REPOSITORY: ${{ vars.NODE_REPOSITORY }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.5.0

      - name: Get branch name and commit SHA
        id: get-branch
        uses: ./.github/actions/get-branch


      - name: Checkout project-template-apps-argocd repository
        uses: actions/checkout@master
        with:
          repository: mikogs/project-template-apps-argocd
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: "project-template-apps-argocd"
          submodules: "recursive"

      - name: Create featureenv argocd application in project-template-apps-argocd
        run: |
          cd project-template-apps-argocd
          ./delete-feature-env.sh ${{ steps.get-branch.outputs.branch_name }}

      - name: Commit changes to project-template-apps-argocd repository
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: project-template
          author_email: project-template@f0x.pl
          message: "Delete featureenv ${{ steps.get-branch.outputs.branch_name }}"
          add: "overlays"
          cwd: "project-template-apps-argocd"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}


      - name: Checkout project-template-envs repository
        uses: actions/checkout@master
        with:
          repository: mikogs/project-template-envs
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: "project-template-envs"
          submodules: "recursive"

      - name: Delete featureenv in project-template-envs
        run: |
          cd project-template-envs
          ./delete-feature-env.sh ${{ steps.get-branch.outputs.branch_name }}
          ./update-devnet-argocd.sh
      
      - name: Commit changes to project-template-envs repository
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: project-template
          author_email: project-template@f0x.pl
          message: "Delete featureenv ${{ steps.get-branch.outputs.branch_name }}"
          add: '.'
          cwd: "project-template-envs"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
