name: Push docker image version tag

on:
  push:
    branches-ignore: 
      - '*'
    tags:
      - 'v*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  push-version-tag:
    runs-on: ubuntu-22.04
    env:
      VAR_NODE_REGISTRY: ${{ vars.NODE_REGISTRY }}
      SECRET_NODE_REGISTRY_USERNAME: ${{ secrets.NODE_REGISTRY_USER }}
      SECRET_NODE_REGISTRY_PASSWORD: ${{ secrets.NODE_REGISTRY_PASS }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.5.0

      - name: Get branch name and commit SHA
        id: get-branch
        uses: ./.github/actions/get-branch

      - name: Login to docker registry
        if: env.VAR_NODE_REGISTRY != '' && env.SECRET_NODE_REGISTRY_USERNAME != '' && env.SECRET_NODE_REGISTRY_PASSWORD != ''
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.NODE_REGISTRY }}
          username: ${{ secrets.SECRET_NODE_REGISTRY_USERNAME }}
          password: ${{ secrets.SECRET_NODE_REGISTRY_PASSWORD }}

      - name: Push docker image to the repository
        if: env.VAR_NODE_REGISTRY != '' && env.SECRET_NODE_REGISTRY_USERNAME != '' && env.SECRET_NODE_REGISTRY_PASSWORD != ''
        run: |
          docker pull ${{ vars.NODE_REGISTRY }}:{{ steps.get-branch.outputs.sha_short }}
          docker tag ${{ vars.NODE_REGISTRY }}:{{ steps.get-branch.outputs.sha_short }} ${{ vars.NODE_REGISTRY }}:{{ steps.get-branch.outputs.branch_name }}
          docker push ${{ vars.NODE_REGISTRY }}:{{ steps.get-branch.outputs.branch_name }}
